# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/carbon/carbon.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lib/carbon/carbon.proto',
  package='carbon',
  serialized_pb='\n\x17lib/carbon/carbon.proto\x12\x06\x63\x61rbon\"=\n\tDatapoint\x12\x0e\n\x06metric\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x02\x12\x11\n\ttimestamp\x18\x03 \x02(\x02')




_DATAPOINT = _descriptor.Descriptor(
  name='Datapoint',
  full_name='carbon.Datapoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metric', full_name='carbon.Datapoint.metric', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='carbon.Datapoint.value', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='carbon.Datapoint.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['Datapoint'] = _DATAPOINT

class Datapoint(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATAPOINT

  # @@protoc_insertion_point(class_scope:carbon.Datapoint)


# @@protoc_insertion_point(module_scope)
