#!/bin/sh

set -e

basedir="$(dirname $0)/.."
cd "$basedir"

command -v virtualenv >/dev/null ||
  pip install virtualenv

[ -f bin/activate ] || (
    virtualenv .
)

. bin/activate

venv="$basedir"
pyver=$(python -V 2>&1 | awk '{gsub(/\.[0-9]+$/,"",$0);print $2}')

#[ "$pyver" = "2.6" ] && bin/pip install argparse
bin/pip install -r requirements.txt --use-mirrors

script/build
