#!/bin/sh

set -e

basedir="$(dirname $0)/.."
cd "$basedir"

if [ ! -f bin/activate ] ; then
  echo 'Please run script/bootstrap first.' >&2
  exit 1
fi

. bin/activate

venv="$basedir"
pyver=$(python -V 2>&1 | awk '{gsub(/\.[0-9]+$/,"",$0);print $2}')

#[ "$pyver" = "2.6" ] && bin/pip install argparse
protoc --python_out . lib/carbon/carbon.proto
bin/python setup.py install --prefix=${venv} --install-lib=${venv}/lib/python${pyver}/site-packages
